apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: execute-aws-secret-list
  title: Listar Segredos Na AWS
  description: Criar Aplicação e recursos
spec:
  owner: samuel
  type: service
  parameters:
    - title: Formulário da aplicação
      description: Responda as questões abaixo referente a aplicação
      required:
        - APP_NAME
        - ENVIROMENT
        - NAMESPACE
      properties:
        APP_NAME:
          title: Nome da aplicação
          type: string
          
        ENVIROMENT:
          title: Informe o Ambiente
          type: string
          default: dev
          enum:
            - dev
            
        NAMESPACE:
          title: Namespace de destino da aplicação
          type: string

  steps:
    - id: bash-data-processing
      name: Processando dados
      action: sh
      command: |
        
      

  output:
    text:
      - title: Informação
