apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: meu-teste-com-erro
  title: meu teste com erro
  description: meu teste com erro
spec:
  owner: samuel
  type: service
  parameters:
    - title: Ambiente de Destino e Opções
      required: [environment]
      properties:
        environment:
          title: Ambiente
          type: string
          enum: [dev-stg, dev, prod, stg]
          default: dev
  steps:
    - id: print-hello
      name: print helo
      action: sh
      input:
        command: |
          $PALAVRA=${{ parameters.environment }}"
          echo "$PALAVRA"
          
  output:
    text:
      - title: Informação
