apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: meu-teste
  title: meu teste
  description: meu teste
spec:
  owner: samuel
  type: service
  parameters:
    - title: print hello
      description: print hello

  steps:
    - id: print-hello
      name: print helo
      action: sh
      input:
        command: |
          echo "hello"
  output:
    text:
      - title: Informação
